### ISSUE TITLE
Flat-Square request (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [badges/poser#10]
Hi, 
I hope you can implement for example `?style=flat-square` parameter for svg as flat-square style.

[![image](https://cloud.githubusercontent.com/assets/1700322/11170059/a3950f4e-8b97-11e5-95e6-404ccd9bd7c9.png)](https://img.shields.io/badge/style-flat--square-green.svg?style=flat-square)

> From https://github.com/PUGX/badge-poser/issues/143

**Comment by jmleroux** [comment]
To be closed

**Comment by liuggio** [comment]
thanks @jmleroux

**Comment by jordanbrauer** [comment]
Thanks for the composer badges! Much needed.

I realized that the .lock badge has no flat style when requesting it with the `?format=flat-square` parameter.
