### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by mnapoli** [badges/poser#2]
Hi there,

Is it possible to tag a stable release from master?

Cheers!

**Comment by liuggio** [comment]
yes,
so easy, if your repository is on github create a release with the stable sintax name eg. `v2.0`, more info at:  https://getcomposer.org/doc/01-basic-usage.md#package-versions

**Comment by mnapoli** [comment]
Ha sorry for the misunderstanding I meant could you create a stable release for [this project](https://github.com/badges/poser/releases) ;)

I am using this library is [isitmaintained.com](http://isitmaintained.com) and using a stable version would be better.

**Comment by liuggio** [comment]
:+1:  https://github.com/badges/poser/releases/tag/v1.0
done

**Comment by mnapoli** [comment]
Thank you :) :smile:
