### ISSUE TITLE
New major version?

### ISSUE THREAD

**Issue by garak** [badges/poser#31]
I guess it's time to raise requirements, allow some new features (e.g. Symfony 5) and drop unsupported deps

**Comment by JellyBellyDev** [comment]
Totally agree!
I try to write a roadmap:

- [ ] create a feature branch `enhancement-v2`
- [ ] upgrade php to 7.4 drop unsupported deps
- [ ] upgrade docker-compose for dev environment
- [ ] move require `ext-gd` to `suggest` section
- [ ] refactoring library to full typed
- [ ] other?
- [ ] merge and tag v2.0.0

what do you think?
