### ISSUE TITLE
Adding new style for the badge

### ISSUE THREAD

**Issue by Karthik-Nayak98** [badges/poser#55]
Can you add **for-the-badge** style as a new style for the badges?
![](https://img.shields.io/badge/style-for--the--badge-green?logo=appveyor&style=for-the-badge)

**Comment by antonkomarev** [comment]
I think it could be implemented without logo images at first because we are not supporting logo images in other badges at this moment

**Comment by KarthikNayak024** [comment]
The logo was just for example. Try to implement it without logo

**Comment by KarthikNayak024** [comment]
If you can guide me I might help you to add this feature.

**Comment by JellyBellyDev** [comment]
Done, thanks to @ricardoboss 🚀
