### ISSUE TITLE
Removal of symlinks in the bin folder

### ISSUE THREAD

**Issue by GregOriol** [badges/poser#61]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | maybe
| Library Version | any
| PHP version     | any

#### Summary

I'd like to suggest the removal of the symlinks in the bin/ folder:
1/ the files should be available in ./vendor/bin/ which is quite standard and common (ie. remove the "bin-dir" configuration in the composer.json)
2/ the symlinks are generated by composer anyway, so they should not be commited to the repository

**Comment by JellyBellyDev** [comment]
Done! Thanks!
