### ISSUE TITLE
Add PHP 8 tests

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [badges/poser#66]
### Feature Request

It could be useful to add to circleCI another image with PHP8 to check if everything it's ok or not, what do you think?
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

**Comment by JellyBellyDev** [comment]
@AlessandroMinoccheri good idea! 
I added you to pugx organization on dockerhub!
you should be able to add a new image [here](https://hub.docker.com/repository/docker/pugx/poser), for use in the pipeline! ;)

**Comment by JellyBellyDev** [comment]
We might take this opportunity to make some order. Going to use the same images for both CI and development!

**Comment by AlessandroMinoccheri** [comment]
Using the same images for both CI and development could be amazing 👍 
Let's do it!

**Comment by AlessandroMinoccheri** [comment]
Closed by #69 and #68
