### ISSUE TITLE
Release v2.1.0 on packagist?

### ISSUE THREAD

**Issue by GregOriol** [badges/poser#75]
Hi,

It seems that v2.1.0 has been released on GitHub but not yet on packagist, so composer doesn't install it right now. Could you release it there too?

**Comment by JellyBellyDev** [comment]
Thanks for the tip! Now i click on the update button! :)

![Schermata 2021-07-16 alle 11 04 17](https://user-images.githubusercontent.com/190820/125922805-f336b814-f4f7-4ec6-821a-8174f897eb53.png)
