### ISSUE TITLE
Avoid using GD module to render SVG images

### ISSUE THREAD

**Issue by antonkomarev** [badges/poser#96]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

These renderers `SvgPlasticRender`, `SvgFlatRender`, `SvgFlatSquareRender` depends on GD library despite the fact they are rendering to SVG. On my machine system library libgd was broken and I found that I cannot generate SVG images, what was unexpected. `SvgForTheBadgeRenderer` working without GD.

#### Current behavior

`SvgPlasticRender`, `SvgFlatRender`, `SvgFlatSquareRender` using GD to compute text width (they are using `GDTextSizeCalculator`).

#### Expected behavior

We are not using GD for the SVG generation.

Then we will be able to drop `"ext-gd": "*"` dependency.

**Comment by garak** [comment]
The renderers use the `GDTextSizeCalculator` class, which needs GD in order to call the `imagettfbbox` method.

**Comment by antonkomarev** [comment]
I suppose it's not a bug, but feature request.

**Comment by antonkomarev** [comment]
> The renderers use the `GDTextSizeCalculator` class, which needs GD in order to call the `imagettfbbox` method.

Exactly. And `SvgForTheBadgeRenderer` using SVG fonts and don't need to use GD to compute text width.

**Comment by garak** [comment]
Do you have an alternate solution to propose? If so, feel free to open a PR

**Comment by antonkomarev** [comment]
I've implemented raw solution locally, need to cleanup code and then will provide a PR.
